project:
  type: website
  output-dir: _site 

format:
  revealjs:
    theme: [simple, style.scss]
    incremental: true
    slide-number: true
    chalkboard: true
    preview-links: auto
    margin: 0.07
    code-link: true
    code-line-numbers: false
    height: 900
    width: 1600

execute:
  echo: true
  eval: true
